version: 0.2

phases:
    install: 
        commands:
            - curl -sL https://deb.nodesource.com/setup_12.x | bash -
            - apt-get install -y nodejs
            - echo installed nodejs
    pre-build:
        commands:
            - npm i
            - npm install typescript@">=3.1.1 <3.3"
    build:
        commands:
            - npm run build

artifacts:
    files:
        - "**/*"
    discard-paths: no
    base-directory: dist